package org.tornotron.echno_backend.category;

import java.util.List;

/**
 * The standard sub-categories under each standard work category, as the product team supplied
 * them (ClickUp 86d4609f9: 215 sub-categories under the 28 categories in
 * {@link WorkCategorySeeder#STANDARD_CATEGORIES}). Order is the order of that list and is the
 * order they appear in the task form. Changeset {@code 130-backfill-standard-work-subcategories}
 * carries the same list for organizations that existed before it.
 */
final class StandardWorkSubcategories {

    /** One standard sub-category: the name shown in the dropdown and its one-line description. */
    record StandardSubcategory(String name, String description) {}

    /** The sub-categories of one standard category, keyed by that category's name. */
    record CategorySubcategories(String category, List<StandardSubcategory> subcategories) {}

    static final List<CategorySubcategories> ALL = List.of(
            new CategorySubcategories("Preliminaries & Site Setup", List.of(
                    new StandardSubcategory("Site mobilization",
                            "Transporting and deploying manpower, plant, machinery, and initial materials to site to establish resources required to commence construction."),
                    new StandardSubcategory("Site office/setup",
                            "Provision of site offices, meeting rooms, and administrative accommodation, including furniture, fittings, and services for project staff and consultants."),
                    new StandardSubcategory("Temporary facilities",
                            "Erection of temporary structures such as labour accommodation, stores, workshops, canteens, and toilets required for the duration of the works."),
                    new StandardSubcategory("Surveying & setting out",
                            "Establishing benchmarks, grid lines, and levels, and marking out building positions and reference points in accordance with approved drawings."),
                    new StandardSubcategory("Site fencing",
                            "Provision of temporary boundary fencing, hoarding, barricades, and gates to enclose, demarcate, and secure the site perimeter."),
                    new StandardSubcategory("Safety arrangements",
                            "Provision of site safety signage, barricading, first-aid facilities, and safety equipment to comply with statutory and project HSE requirements."),
                    new StandardSubcategory("Temporary utilities",
                            "Arranging temporary water, power, lighting, and drainage connections, including distribution within the site for construction use."))),
            new CategorySubcategories("Earthwork", List.of(
                    new StandardSubcategory("Site clearing",
                            "Clearing the site of vegetation, trees, shrubs, debris, and existing obstructions, including grubbing of roots and disposal of cleared material."),
                    new StandardSubcategory("Excavation",
                            "Removal of soil or rock to specified depths and dimensions for foundations, basements, trenches, and other construction works."),
                    new StandardSubcategory("Earth cutting",
                            "Cutting of existing ground to required formation levels and profiles, including slope trimming for platforms, embankments, and roadways."),
                    new StandardSubcategory("Soil removal",
                            "Loading, hauling, and disposal of surplus or unsuitable excavated soil to approved dumping areas within or outside the site."),
                    new StandardSubcategory("Backfilling",
                            "Placement and compaction of approved soil or fill material around foundations, structures, trenches, and excavated areas."),
                    new StandardSubcategory("Filling",
                            "Supply, spreading, and compaction of approved earth or granular fill in layers to raise ground to the required formation level."),
                    new StandardSubcategory("Soil compaction",
                            "Mechanical compaction of soil or fill in layers to achieve the specified density and bearing capacity as verified by field tests."),
                    new StandardSubcategory("Grading & leveling",
                            "Shaping, trimming, and leveling of ground surfaces to the required levels, gradients, and slopes for drainage and construction."))),
            new CategorySubcategories("Foundation Works", List.of(
                    new StandardSubcategory("PCC",
                            "Laying of plain cement concrete leveling course beneath foundations to provide a clean, level base for reinforcement and footing concrete."),
                    new StandardSubcategory("Isolated footing",
                            "Construction of individual reinforced concrete footings supporting single columns, including formwork, reinforcement, concreting, and curing."),
                    new StandardSubcategory("Combined footing",
                            "Construction of a single reinforced concrete footing supporting two or more columns where individual footings would overlap or be eccentric."),
                    new StandardSubcategory("Strip footing",
                            "Construction of continuous reinforced concrete footings beneath load-bearing walls or closely spaced columns, including reinforcement and concreting."),
                    new StandardSubcategory("Raft foundation",
                            "Construction of a continuous reinforced concrete slab foundation beneath the entire structure to distribute loads over weak or variable soil."),
                    new StandardSubcategory("Pile foundation",
                            "Installation of bored, driven, or cast-in-situ piles to transfer structural loads to deeper bearing strata, including boring, reinforcement, and concreting."),
                    new StandardSubcategory("Pile cap",
                            "Construction of reinforced concrete caps over pile groups to distribute column loads to the piles, including formwork, reinforcement, and concreting."),
                    new StandardSubcategory("Foundation waterproofing",
                            "Application of waterproofing membranes, coatings, or admixtures to foundation and substructure surfaces to prevent moisture and groundwater ingress."),
                    new StandardSubcategory("Foundation backfilling",
                            "Backfilling and compaction of approved material around completed foundations and substructure walls up to the required ground level."))),
            new CategorySubcategories("Concrete Works", List.of(
                    new StandardSubcategory("PCC",
                            "Production and placement of plain cement concrete for leveling courses, blinding layers, bedding, and other non-structural applications."),
                    new StandardSubcategory("RCC",
                            "Placement of reinforced cement concrete structural members using concrete and embedded reinforcement steel."),
                    new StandardSubcategory("Ready-mix concrete",
                            "Supply of batched concrete from a central plant, including transport by transit mixer, testing at site, and placement within permitted time."),
                    new StandardSubcategory("Structural concrete",
                            "Placement of designed-mix concrete in load-bearing members such as columns, beams, slabs, walls, and cores, including compaction and curing."),
                    new StandardSubcategory("Non-structural concrete",
                            "Placement of concrete in non-load-bearing elements such as kerbs, screeds, infill, blinding, and equipment bases."),
                    new StandardSubcategory("Concrete pumping",
                            "Transporting and placing concrete using boom or line pumps for elevated, congested, or otherwise inaccessible pour locations."),
                    new StandardSubcategory("Concrete finishing",
                            "Screeding, floating, trowelling, and texturing of exposed concrete surfaces to achieve the specified level, finish, and tolerance."),
                    new StandardSubcategory("Curing",
                            "Maintaining moisture and temperature in placed concrete by ponding, wet covering, or curing compounds for the specified duration to achieve design strength."))),
            new CategorySubcategories("Reinforcement Works", List.of(
                    new StandardSubcategory("Rebar cutting",
                            "Cutting of reinforcement bars to the lengths required by approved bar bending schedules, including wastage control and offcut management."),
                    new StandardSubcategory("Rebar bending",
                            "Bending of reinforcement bars to the shapes, hooks, and radii specified in approved bar bending schedules using mechanical or manual equipment."),
                    new StandardSubcategory("Rebar fabrication",
                            "Cutting, bending, and assembling of reinforcement into cages and mats at the fabrication yard, ready for placement in structural members."),
                    new StandardSubcategory("Rebar fixing",
                            "Placing, positioning, and tying of reinforcement within formwork with specified cover, spacing, laps, and chairs prior to concreting."),
                    new StandardSubcategory("Reinforcement mesh",
                            "Supply and placement of welded wire fabric in slabs, screeds, and toppings, including overlaps, cover, and support arrangements."),
                    new StandardSubcategory("Couplers",
                            "Installation of mechanical splicing couplers to join reinforcement bars where lapping is impractical, including thread preparation and testing."),
                    new StandardSubcategory("Binding",
                            "Tying of reinforcement bars at intersections with binding wire to hold the cage in position and maintain spacing during concreting."))),
            new CategorySubcategories("Formwork / Shuttering", List.of(
                    new StandardSubcategory("Footing formwork",
                            "Fabrication, erection, alignment, and bracing of formwork for footings and pile caps, including supports and application of release agent."),
                    new StandardSubcategory("Column formwork",
                            "Erection, plumbing, and bracing of column shuttering to required sizes and levels, including clamps, ties, and access provisions."),
                    new StandardSubcategory("Beam formwork",
                            "Erection of beam soffit and side shuttering with props, supports, and camber as required, including alignment and leveling."),
                    new StandardSubcategory("Slab formwork",
                            "Erection of slab shuttering with props, joists, and staging to the required levels, including edge shuttering and openings."),
                    new StandardSubcategory("Wall formwork",
                            "Erection of double-sided wall shuttering with ties, walers, and bracing for shear walls, retaining walls, and cores."),
                    new StandardSubcategory("Staircase formwork",
                            "Erection of shuttering for staircase waists, risers, treads, and landings, including supports and alignment to the specified geometry."),
                    new StandardSubcategory("Formwork removal",
                            "Stripping, cleaning, and stacking of formwork after the specified curing period, including removal of props and back-propping where required."))),
            new CategorySubcategories("Structural Steel Works", List.of(
                    new StandardSubcategory("Steel fabrication",
                            "Cutting, drilling, assembling, and welding of structural steel members in the workshop in accordance with approved fabrication drawings."),
                    new StandardSubcategory("Steel erection",
                            "Lifting, positioning, aligning, and securing of fabricated steel members at site, including temporary bracing and survey checks."),
                    new StandardSubcategory("Structural connections",
                            "Assembly of bolted and welded joints between steel members, including base plates, gussets, splices, and cleats as detailed."),
                    new StandardSubcategory("Welding",
                            "Execution of shop and site welds to approved procedures, including edge preparation, preheating where required, and non-destructive testing."),
                    new StandardSubcategory("Bolting",
                            "Installation and tightening of high-strength and ordinary bolts to the specified torque or tension, including washers, packers, and inspection."),
                    new StandardSubcategory("Steel painting/coating",
                            "Surface preparation and application of primer, intermediate, and finish coats or galvanizing for corrosion and fire protection of steelwork."),
                    new StandardSubcategory("Metal decking",
                            "Laying, aligning, and fixing of profiled metal deck sheets over steel framing to act as permanent formwork and composite slab reinforcement."))),
            new CategorySubcategories("Masonry Works", List.of(
                    new StandardSubcategory("Brick masonry",
                            "Construction of walls using burnt clay or fly-ash bricks laid in cement mortar to the specified thickness, bond, and joint finish."),
                    new StandardSubcategory("Block masonry",
                            "Construction of walls using solid or hollow concrete blocks laid in cement mortar, including reinforcement and grouting where specified."),
                    new StandardSubcategory("AAC block work",
                            "Construction of walls using autoclaved aerated concrete blocks laid in thin-bed adhesive or mortar, including cutting and jointing."),
                    new StandardSubcategory("Stone masonry",
                            "Construction of walls using random rubble, coursed, or dressed stone laid in mortar, including bond stones and joint finishing."),
                    new StandardSubcategory("Partition walls",
                            "Construction of non-load-bearing internal division walls in masonry or drywall to subdivide floor areas as per layout drawings."),
                    new StandardSubcategory("Internal walls",
                            "Construction of masonry walls within the building envelope, including openings, lintels, and bonding to structural members."),
                    new StandardSubcategory("External walls",
                            "Construction of masonry walls forming the building envelope, including openings, lintels, sills, and weather-resistant jointing."))),
            new CategorySubcategories("Plastering & Rendering", List.of(
                    new StandardSubcategory("Internal plaster",
                            "Application of cement or gypsum plaster to internal wall surfaces in the specified coats and thickness, finished smooth and true to line."),
                    new StandardSubcategory("External plaster",
                            "Application of cement plaster to external wall surfaces in the specified coats and thickness, including grooves, drip moulds, and curing."),
                    new StandardSubcategory("Cement rendering",
                            "Application of cement-sand render coats to masonry or concrete surfaces to provide a level, durable base for subsequent finishes."),
                    new StandardSubcategory("Ceiling plaster",
                            "Application of plaster to soffits of slabs and beams, including surface preparation, bonding coat, and finishing to a smooth surface."),
                    new StandardSubcategory("Repair plaster",
                            "Removal of defective plaster and reapplication over patched areas, including surface preparation, bonding, and matching of adjacent finishes."),
                    new StandardSubcategory("Textured rendering",
                            "Application of decorative textured render finishes to internal or external surfaces using specified patterns, tools, and proprietary materials."))),
            new CategorySubcategories("Waterproofing", List.of(
                    new StandardSubcategory("Roof waterproofing",
                            "Application of membrane, coating, or integral waterproofing systems to roof slabs, including surface preparation, priming, and protective screed."),
                    new StandardSubcategory("Toilet waterproofing",
                            "Application of waterproofing to toilet and wet-area floors and skirtings, including sunk slabs, pipe penetrations, and ponding tests."),
                    new StandardSubcategory("Basement waterproofing",
                            "Application of waterproofing systems to basement slabs, walls, and retaining structures to resist hydrostatic pressure and groundwater ingress."),
                    new StandardSubcategory("Terrace waterproofing",
                            "Application of waterproofing treatment to terraces, including slope screeds, coving at junctions, drainage outlets, and protective layers."),
                    new StandardSubcategory("Water tank waterproofing",
                            "Application of non-toxic waterproofing systems to internal surfaces of overhead and underground water tanks, including coving and leak testing."),
                    new StandardSubcategory("Expansion-joint waterproofing",
                            "Sealing of expansion and construction joints with water bars, sealants, and joint systems to maintain watertightness while permitting movement."))),
            new CategorySubcategories("Roofing", List.of(
                    new StandardSubcategory("RCC roof",
                            "Construction of reinforced concrete roof slabs, including formwork, reinforcement, concreting, curing, and slope screeds for drainage."),
                    new StandardSubcategory("Metal roofing",
                            "Supply and fixing of profiled metal roof sheets over purlins, including fasteners, flashings, ridges, gutters, and accessories."),
                    new StandardSubcategory("Tile roofing",
                            "Laying of clay or concrete roof tiles over battens or sloping slabs, including ridges, valleys, hips, and pointing."),
                    new StandardSubcategory("Sheet roofing",
                            "Supply and fixing of fibre cement, polycarbonate, or similar roof sheeting with laps, fasteners, and associated accessories."),
                    new StandardSubcategory("Roof insulation",
                            "Supply and laying of thermal insulation boards or layers over roof surfaces, including vapour barriers and protective coverings."),
                    new StandardSubcategory("Roof drainage",
                            "Provision of rainwater outlets, gutters, downpipes, and slopes to collect and discharge roof water into the drainage system."))),
            new CategorySubcategories("Flooring", List.of(
                    new StandardSubcategory("PCC flooring",
                            "Laying of plain cement concrete floor base to the required thickness and level, including compaction, surface finishing, and curing."),
                    new StandardSubcategory("Tile flooring",
                            "Laying of floor tiles over prepared bases in cement mortar or adhesive, including cutting, spacing, jointing, and grouting."),
                    new StandardSubcategory("Vitrified tiles",
                            "Laying of vitrified floor tiles in adhesive or mortar bed with minimal joints, including skirting, cutting, and epoxy or cement grouting."),
                    new StandardSubcategory("Ceramic tiles",
                            "Laying of glazed or unglazed ceramic floor tiles in adhesive or mortar bed, including skirting, cutting, and grouting."),
                    new StandardSubcategory("Granite",
                            "Supply and laying of polished granite slabs for floors, treads, and skirting, including cutting, edge finishing, jointing, and polishing."),
                    new StandardSubcategory("Marble",
                            "Supply and laying of marble slabs or tiles for floors and skirting, including cutting, jointing, grinding, and mirror polishing."),
                    new StandardSubcategory("Stone flooring",
                            "Laying of natural stone such as kota, sandstone, or slate in mortar bed, including dressing, jointing, and surface finishing."),
                    new StandardSubcategory("Industrial flooring",
                            "Laying of heavy-duty floor systems with hardeners, vacuum dewatering, or toppings to resist abrasion and heavy loading in industrial areas."),
                    new StandardSubcategory("Epoxy flooring",
                            "Application of epoxy self-leveling or coating systems over prepared concrete floors, including priming, coving, and finish coats."),
                    new StandardSubcategory("Vinyl flooring",
                            "Laying of vinyl sheets or tiles over leveled and primed floor bases using adhesive, including welding of joints and skirting."))),
            new CategorySubcategories("Wall Finishes", List.of(
                    new StandardSubcategory("Wall tiles",
                            "Fixing of wall tiles in adhesive or mortar over plastered surfaces, including cutting around fittings, spacing, and grouting."),
                    new StandardSubcategory("Ceramic finishes",
                            "Application of ceramic tile finishes to internal wall surfaces in wet and service areas, including trims, beads, and grouting."),
                    new StandardSubcategory("Stone cladding",
                            "Fixing of natural or engineered stone cladding to walls using mechanical anchors or adhesive, including jointing and sealing."),
                    new StandardSubcategory("Paint",
                            "Application of primer and finish coats of emulsion or other specified paint to prepared wall surfaces in the required number of coats."),
                    new StandardSubcategory("Texture paint",
                            "Application of textured decorative coatings to internal or external walls using specified patterns, tools, and base preparation."),
                    new StandardSubcategory("Wallpaper",
                            "Surface preparation and fixing of wallpaper or wall covering with adhesive, including pattern matching, trimming, and edge sealing."),
                    new StandardSubcategory("Decorative finishes",
                            "Application of special wall treatments such as veneer, laminate, fabric, metal, or panel systems as per interior design drawings."))),
            new CategorySubcategories("Ceiling Works", List.of(
                    new StandardSubcategory("False ceiling",
                            "Installation of suspended ceiling systems with framing, hangers, and panels to conceal services and achieve the specified ceiling level."),
                    new StandardSubcategory("Gypsum ceiling",
                            "Installation of gypsum board ceilings on GI framing, including jointing, taping, finishing, cutouts, and coves as detailed."),
                    new StandardSubcategory("Grid ceiling",
                            "Installation of exposed or concealed grid systems with mineral fibre or similar lay-in tiles, including perimeter trims and service cutouts."),
                    new StandardSubcategory("Metal ceiling",
                            "Installation of metal ceiling panels, planks, or baffles on suspension systems, including perforations, acoustic backing, and trims."),
                    new StandardSubcategory("Ceiling insulation",
                            "Supply and placement of thermal or acoustic insulation above ceilings, including vapour barriers and support arrangements."),
                    new StandardSubcategory("Ceiling painting",
                            "Surface preparation and application of primer and finish coats to ceiling surfaces in the specified number of coats and finish."))),
            new CategorySubcategories("Doors & Windows", List.of(
                    new StandardSubcategory("Wooden doors",
                            "Supply and installation of timber door frames and shutters, including hinges, hardware, finishing, and adjustment for smooth operation."),
                    new StandardSubcategory("Metal doors",
                            "Supply and installation of steel or metal door frames and shutters, including hardware, priming, painting, and fixing to the structure."),
                    new StandardSubcategory("UPVC doors/windows",
                            "Supply and installation of UPVC frames, sashes, and glazing, including hardware, sealing, and weatherproofing of joints."),
                    new StandardSubcategory("Aluminium doors/windows",
                            "Supply and installation of aluminium framed doors and windows with glazing, gaskets, hardware, and sealant to the structure."),
                    new StandardSubcategory("Glass doors",
                            "Supply and installation of toughened or laminated glass doors, including patch fittings, floor springs, handles, and locking arrangements."),
                    new StandardSubcategory("Curtain wall",
                            "Fabrication and installation of structural glazed facade systems, including brackets, mullions, transoms, glazing, and weather sealing."),
                    new StandardSubcategory("Hardware & fittings",
                            "Supply and fixing of locks, hinges, closers, handles, stoppers, and associated ironmongery for doors and windows."))),
            new CategorySubcategories("Painting Works", List.of(
                    new StandardSubcategory("Interior painting",
                            "Preparation and painting of internal walls and ceilings with primer and specified finish coats to the required shade and sheen."),
                    new StandardSubcategory("Exterior painting",
                            "Preparation and painting of external surfaces with weather-resistant primer and finish coats, including access arrangements and surface repairs."),
                    new StandardSubcategory("Primer",
                            "Application of primer coats over prepared surfaces to improve adhesion, seal porosity, and provide a uniform base for subsequent coats."),
                    new StandardSubcategory("Putty",
                            "Application of wall putty to fill minor undulations and achieve a smooth, level surface, including sanding between coats."),
                    new StandardSubcategory("Enamel painting",
                            "Application of enamel paint over primed wood and metal surfaces to provide a hard, glossy, and washable finish."),
                    new StandardSubcategory("Protective coating",
                            "Application of specialized coatings for corrosion, chemical, abrasion, or fire protection of steel, concrete, and other substrates."),
                    new StandardSubcategory("Waterproof coating",
                            "Application of water-resistant coatings to external walls and surfaces to reduce water penetration and dampness."))),
            new CategorySubcategories("Plumbing", List.of(
                    new StandardSubcategory("Water supply",
                            "Installation of internal and external water supply piping, valves, and fittings from source to fixtures, including pressure testing."),
                    new StandardSubcategory("Drainage",
                            "Installation of soil, waste, and vent piping with traps, gullies, and manholes to convey wastewater to the disposal system."),
                    new StandardSubcategory("Sanitary piping",
                            "Installation of sanitary pipework connecting fixtures to the drainage system, including slopes, cleanouts, and leak testing."),
                    new StandardSubcategory("Stormwater drainage",
                            "Installation of rainwater pipes, channels, catch basins, and outfalls to collect and discharge stormwater from roofs and paved areas."),
                    new StandardSubcategory("Pumps",
                            "Supply, installation, and connection of water supply, sump, and booster pumps, including bases, piping, controls, and performance testing."),
                    new StandardSubcategory("Water tanks",
                            "Supply and installation of overhead and underground water storage tanks, including supports, inlet and outlet piping, and level controls."),
                    new StandardSubcategory("Sanitary fixtures",
                            "Supply and installation of water closets, wash basins, urinals, and sinks, including fixing accessories, sealing, and testing."),
                    new StandardSubcategory("Plumbing fixtures",
                            "Supply and installation of taps, mixers, showers, traps, and associated fittings, including connection and testing for leaks."))),
            new CategorySubcategories("Electrical Works", List.of(
                    new StandardSubcategory("Electrical conduits",
                            "Laying of concealed or surface conduits with junction boxes and accessories in slabs, walls, and floors for cable routing."),
                    new StandardSubcategory("Wiring",
                            "Drawing and terminating of wires through conduits to switches, sockets, and fixtures, including looping, identification, and insulation testing."),
                    new StandardSubcategory("Cable laying",
                            "Laying of power and control cables in trenches, trays, or ducts, including supports, glanding, termination, and testing."),
                    new StandardSubcategory("Distribution boards",
                            "Supply and installation of main and sub distribution boards with breakers, busbars, and labeling, including termination of incoming and outgoing circuits."),
                    new StandardSubcategory("Switches & sockets",
                            "Installation of switches, socket outlets, and control accessories with boxes and plates, including connection and functional testing."),
                    new StandardSubcategory("Lighting",
                            "Supply and installation of light fixtures with mounting accessories, wiring connections, controls, and illumination testing."),
                    new StandardSubcategory("Earthing",
                            "Installation of earth pits, electrodes, and earth conductors bonded to equipment and structures, including measurement of earth resistance."),
                    new StandardSubcategory("Lightning protection",
                            "Installation of air terminals, down conductors, and earth terminations to protect the structure against lightning strikes."),
                    new StandardSubcategory("Generator connection",
                            "Installation of cabling, changeover panels, and controls to connect standby generators to the electrical distribution system."))),
            new CategorySubcategories("HVAC", List.of(
                    new StandardSubcategory("Ducting",
                            "Fabrication and installation of sheet metal ducts with supports, insulation, dampers, grilles, and diffusers for air distribution."),
                    new StandardSubcategory("Chilled water piping",
                            "Installation of chilled water supply and return piping with valves, supports, insulation, and pressure testing."),
                    new StandardSubcategory("Refrigerant piping",
                            "Installation of copper refrigerant piping between indoor and outdoor units, including brazing, insulation, pressure testing, and charging."),
                    new StandardSubcategory("AHU",
                            "Supply, installation, and connection of air handling units, including foundations, duct connections, drain piping, and commissioning."),
                    new StandardSubcategory("FCU",
                            "Supply and installation of fan coil units with supports, duct and pipe connections, drain lines, thermostats, and testing."),
                    new StandardSubcategory("VRF/VRV",
                            "Installation of variable refrigerant flow systems including outdoor units, indoor units, refrigerant piping, controls, and commissioning."),
                    new StandardSubcategory("Ventilation",
                            "Installation of fresh air, exhaust, and pressurization systems with fans, ducts, louvres, and controls to achieve design air changes."),
                    new StandardSubcategory("HVAC controls",
                            "Installation of sensors, thermostats, actuators, and control panels to regulate HVAC equipment, including wiring and integration."))),
            new CategorySubcategories("Fire & Life Safety", List.of(
                    new StandardSubcategory("Fire hydrant",
                            "Installation of hydrant piping, landing valves, hose reels, and cabinets with associated pumps and connections, including pressure testing."),
                    new StandardSubcategory("Sprinkler system",
                            "Installation of sprinkler piping, heads, valves, and flow switches, including hydraulic testing and coordination with ceiling layouts."),
                    new StandardSubcategory("Fire alarm",
                            "Installation of detectors, sounders, call points, cabling, and control panels, including addressing, programming, and functional testing."),
                    new StandardSubcategory("Fire extinguishers",
                            "Supply, mounting, and commissioning of portable fire extinguishers of the specified types and capacities at designated locations."),
                    new StandardSubcategory("Fire pumps",
                            "Supply and installation of main, jockey, and standby fire pumps with panels, piping, and controls, including performance testing."),
                    new StandardSubcategory("Fire-rated doors",
                            "Supply and installation of certified fire-rated door assemblies with frames, seals, closers, and hardware to the specified rating."),
                    new StandardSubcategory("Emergency lighting",
                            "Installation of emergency luminaires and exit signage with battery backup, wiring, and testing to maintain illumination during power failure."),
                    new StandardSubcategory("Fire stopping",
                            "Sealing of service penetrations and joints in fire-rated walls and floors with approved fire-stop materials to maintain compartmentation."))),
            new CategorySubcategories("ELV / Low Voltage Systems", List.of(
                    new StandardSubcategory("CCTV",
                            "Installation of cameras, cabling, recorders, and monitors, including mounting, configuration, and verification of coverage."),
                    new StandardSubcategory("Access control",
                            "Installation of card readers, controllers, electric locks, and cabling, including integration, programming, and door release testing."),
                    new StandardSubcategory("Networking",
                            "Installation of network switches, racks, and active equipment, including configuration, patching, and connectivity testing."),
                    new StandardSubcategory("Structured cabling",
                            "Installation of data and voice cabling with racks, patch panels, outlets, and labeling, including termination and certification testing."),
                    new StandardSubcategory("Public address",
                            "Installation of amplifiers, speakers, and cabling for announcements and evacuation messaging, including zoning and audibility testing."),
                    new StandardSubcategory("Intercom",
                            "Installation of intercom and video door phone systems with panels, cabling, and handsets, including configuration and testing."),
                    new StandardSubcategory("Building management system",
                            "Installation of BMS controllers, field devices, and cabling to monitor and control building services, including integration and graphics."),
                    new StandardSubcategory("Security systems",
                            "Installation of intrusion detection, perimeter security, and alarm devices with cabling, panels, and integration to monitoring stations."))),
            new CategorySubcategories("External Development", List.of(
                    new StandardSubcategory("Roads",
                            "Construction of internal roads with subgrade preparation, sub-base, base course, and bituminous or concrete wearing surface."),
                    new StandardSubcategory("Paving",
                            "Laying of paver blocks, tiles, or slabs over prepared bases with sand bedding, edge restraints, jointing, and compaction."),
                    new StandardSubcategory("Footpaths",
                            "Construction of pedestrian walkways with base preparation, surfacing, edging, and finishing to the required levels and gradients."),
                    new StandardSubcategory("Kerbs",
                            "Casting or laying of precast kerb stones and channels along roads and paved areas, including bedding, haunching, and jointing."),
                    new StandardSubcategory("Parking",
                            "Construction of surface parking areas including base, surfacing, line marking, wheel stops, signage, and drainage."),
                    new StandardSubcategory("Drainage",
                            "Construction of external drainage networks with pipes, channels, catch pits, and manholes to collect and discharge surface water."),
                    new StandardSubcategory("Boundary walls",
                            "Construction of perimeter walls in masonry or concrete with foundations, columns, coping, and finishes as specified."),
                    new StandardSubcategory("Gates",
                            "Supply and installation of main and service gates with frames, hinges, locking, and operating mechanisms including automation where specified."),
                    new StandardSubcategory("Landscaping",
                            "Development of soft and hard landscape areas including soil preparation, planting, turfing, irrigation, and landscape features."))),
            new CategorySubcategories("Utilities & Infrastructure", List.of(
                    new StandardSubcategory("Water supply network",
                            "Laying of external water mains with valves, chambers, and connections from source to buildings, including testing and disinfection."),
                    new StandardSubcategory("Sewerage",
                            "Laying of external sewer lines with manholes, chambers, and connections to the treatment plant or municipal network, including testing."),
                    new StandardSubcategory("Stormwater",
                            "Construction of external stormwater networks with pipes, culverts, catch basins, and outfalls to manage site runoff."),
                    new StandardSubcategory("Electrical infrastructure",
                            "Installation of external power distribution including HT and LT cabling, panels, feeder pillars, and street lighting networks."),
                    new StandardSubcategory("Transformer works",
                            "Supply, installation, and commissioning of transformers with plinths, oil filling, protection, cabling, and testing."),
                    new StandardSubcategory("DG installation",
                            "Installation of diesel generator sets with foundations, exhaust, fuel systems, acoustic enclosure, panels, and load testing."),
                    new StandardSubcategory("Utility trenches",
                            "Excavation, bedding, laying, and backfilling of trenches for utility services, including warning tapes, ducts, and marker posts."))),
            new CategorySubcategories("Specialized Works", List.of(
                    new StandardSubcategory("Lift/elevator",
                            "Supply, installation, and commissioning of passenger or goods lifts, including guide rails, machine, car, doors, controls, and statutory testing."),
                    new StandardSubcategory("Escalator",
                            "Supply, installation, and commissioning of escalators or moving walkways, including support structure, drive, balustrades, and safety devices."),
                    new StandardSubcategory("Solar PV",
                            "Installation of solar photovoltaic modules, mounting structures, inverters, cabling, and metering, including grid connection and performance testing."),
                    new StandardSubcategory("Solar water heating",
                            "Installation of solar collectors, storage tanks, piping, and controls for hot water generation, including insulation and testing."),
                    new StandardSubcategory("Building automation",
                            "Installation and integration of automated control systems for lighting, HVAC, and building services, including programming and commissioning."),
                    new StandardSubcategory("Acoustic works",
                            "Installation of acoustic insulation, panels, baffles, and treatments to achieve the specified sound absorption and noise isolation levels."),
                    new StandardSubcategory("Clean-room works",
                            "Construction of controlled environment areas with modular panels, sealed finishes, filtration, and pressurization to the specified cleanliness class."),
                    new StandardSubcategory("Specialized industrial installations",
                            "Installation of process equipment, industrial plant, and associated supports and services specific to the facility's operations."))),
            new CategorySubcategories("Testing, Commissioning & Handover", List.of(
                    new StandardSubcategory("Material testing",
                            "Sampling and laboratory testing of construction materials to verify conformity with specifications and approved standards."),
                    new StandardSubcategory("Concrete testing",
                            "Testing of fresh and hardened concrete including slump, cube compressive strength, and non-destructive tests as specified."),
                    new StandardSubcategory("Electrical testing",
                            "Testing of electrical installations including insulation resistance, earth resistance, continuity, and load tests prior to energization."),
                    new StandardSubcategory("Plumbing testing",
                            "Pressure, leak, and flow testing of water supply and drainage systems, including flushing, disinfection, and ball testing of pipes."),
                    new StandardSubcategory("HVAC testing",
                            "Testing, adjusting, and balancing of air and water systems to achieve design flow rates, temperatures, and pressures."),
                    new StandardSubcategory("Fire-system testing",
                            "Testing of fire detection, alarm, hydrant, and sprinkler systems, including pressure tests, functional trials, and statutory inspections."),
                    new StandardSubcategory("Equipment commissioning",
                            "Pre-commissioning checks, start-up, and performance verification of installed equipment and systems under operating conditions."),
                    new StandardSubcategory("Snagging",
                            "Systematic inspection of completed works to identify defects, incomplete items, and deviations, recorded in a snag list for rectification."),
                    new StandardSubcategory("Rectification",
                            "Correction of defects and incomplete works identified during inspection or snagging, including re-inspection and closure of items."),
                    new StandardSubcategory("As-built documentation",
                            "Preparation and submission of as-built drawings, test records, warranties, and operation and maintenance manuals reflecting the works as constructed."),
                    new StandardSubcategory("Handover",
                            "Formal transfer of the completed works to the client, including documentation, keys, training, and issue of completion certificates."))),
            new CategorySubcategories("Demolition & Renovation", List.of(
                    new StandardSubcategory("Structural demolition",
                            "Controlled demolition of load-bearing elements such as columns, beams, slabs, and walls, including propping and safety measures."),
                    new StandardSubcategory("Non-structural demolition",
                            "Removal of non-load-bearing elements such as partitions, finishes, false ceilings, and fixtures without affecting structural stability."),
                    new StandardSubcategory("Dismantling",
                            "Careful removal of components, fittings, and installations for reuse or relocation, including labeling, handling, and storage."),
                    new StandardSubcategory("Debris removal",
                            "Collection, loading, and transportation of demolition waste and debris to approved disposal or recycling facilities."),
                    new StandardSubcategory("Renovation",
                            "Upgrading or remodeling of existing spaces including alterations, new finishes, and modification of services to meet revised requirements."),
                    new StandardSubcategory("Repair",
                            "Repair of damaged or deteriorated building elements, including crack repair, patching, and replacement of defective components."),
                    new StandardSubcategory("Retrofitting",
                            "Strengthening of existing structures using jacketing, plating, fibre wrapping, or bracing to enhance capacity or seismic performance."),
                    new StandardSubcategory("Restoration",
                            "Reinstatement of existing or heritage elements to their original condition using matching materials, techniques, and finishes."))),
            new CategorySubcategories("Site Logistics", List.of(
                    new StandardSubcategory("Material unloading",
                            "Receiving and unloading of delivered materials at site, including inspection, verification against delivery notes, and stacking."),
                    new StandardSubcategory("Material handling",
                            "Movement of materials between storage and work areas using manual labour, trolleys, forklifts, or other handling equipment."),
                    new StandardSubcategory("Internal transportation",
                            "Transport of materials, equipment, and debris within the site boundary, including maintenance of access routes and haul roads."),
                    new StandardSubcategory("Equipment movement",
                            "Mobilizing, positioning, and relocating of construction plant and equipment within the site, including access preparation."),
                    new StandardSubcategory("Crane operations",
                            "Deployment and operation of tower or mobile cranes for lifting and placing materials, including rigging, signalling, and load planning."),
                    new StandardSubcategory("Hoisting",
                            "Vertical movement of materials and personnel using hoists, winches, or lifting devices, including installation and safety checks."),
                    new StandardSubcategory("Storage management",
                            "Organized stacking and storage of materials in designated areas with protection from weather, damage, and pilferage."),
                    new StandardSubcategory("Waste management",
                            "Segregation, collection, storage, and disposal of construction waste, including recycling and record keeping."))),
            new CategorySubcategories("Safety & Environmental", List.of(
                    new StandardSubcategory("PPE",
                            "Provision, issue, and enforcement of personal protective equipment such as helmets, footwear, harnesses, gloves, and eye protection."),
                    new StandardSubcategory("Scaffolding safety",
                            "Erection, inspection, tagging, and dismantling of scaffolding with guardrails, base plates, ties, and safe access platforms."),
                    new StandardSubcategory("Fall protection",
                            "Provision of edge protection, safety nets, lifelines, and anchorage points for work at height, including inspection and training."),
                    new StandardSubcategory("Dust control",
                            "Measures to suppress airborne dust such as water sprinkling, screening, covering of materials, and wheel washing."),
                    new StandardSubcategory("Noise control",
                            "Measures to limit construction noise including equipment silencers, barriers, restricted working hours, and monitoring."),
                    new StandardSubcategory("Waste disposal",
                            "Disposal of construction and hazardous waste through approved channels in compliance with environmental regulations, including documentation."),
                    new StandardSubcategory("Environmental monitoring",
                            "Periodic monitoring of air, water, noise, and soil parameters to verify compliance with environmental limits and permit conditions."),
                    new StandardSubcategory("Site housekeeping",
                            "Routine cleaning, clearing of access routes, and maintenance of orderly work areas to support safe and efficient operations.")))
    );

    private StandardWorkSubcategories() {
    }
}
