global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app-echno-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']