package org.tornotron.echno_backend.pdfGeneration;

import org.openpdf.text.*;
import org.openpdf.text.Font;
import org.openpdf.text.pdf.PdfPCell;
import org.openpdf.text.pdf.PdfPTable;
import org.openpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import org.tornotron.echno_backend.employee.Employee;
import org.tornotron.echno_backend.employee.EmployeeRepository;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.util.Date;
import java.util.List;

@Service
public class ReportService {

    private final EmployeeRepository employeeRepository;

    public ReportService(EmployeeRepository employeeRepository) {
        this.employeeRepository = employeeRepository;
    }

    public byte[] generatePdfReport() {
        List<Employee> employees = employeeRepository.findAll();

        ByteArrayOutputStream boas = new ByteArrayOutputStream();

        Document document = new Document(PageSize.A4);

        try {
            PdfWriter.getInstance(document, boas);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Paragraph title = new Paragraph("Employee Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.setSpacingBefore(25f);
            table.setSpacingAfter(25f);

            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);

            addTableHeader(table, "ID", headerFont);
            addTableHeader(table, "Name", headerFont);
            addTableHeader(table, "Department", headerFont);
            addTableHeader(table, "Salary", headerFont);

            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA,12);
            for (Employee emp :employees) {
                addTableCell(table, emp.getId().toString(), cellFont);
                addTableCell(table, emp.getEmployeeName(), cellFont);
                addTableCell(table, emp.getDepartment(), cellFont);
                addTableCell(table, emp.getSalary().toString(),cellFont);
            }

            document.add(table);

            Paragraph footer = new Paragraph("Generated by Echno: "+new Date(),cellFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
        } catch (DocumentException e) {
            throw new DocumentException("Error creating PDF document");
        }

        return boas.toByteArray();
    }

    private void addTableHeader(PdfPTable table, String headerTitle, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(headerTitle, font));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(Color.LIGHT_GRAY);
        table.addCell(cell);
    }

    private void addTableCell(PdfPTable table, String content, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(content,font));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }
}
