jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_BACKEND_CLIENT}
      principle-attribute: preferred_username

digital-ocean:
  uri: ${DIGITAL_OCEAN_SPACES_URI}
  access-key-id: ${DIGITAL_OCEAN_SPACES_KEY_ID}
  secret-access-key: ${DIGITAL_OCEAN_SPACES_KEY_SECRET}
  bucket-name: ${DIGITAL_OCEAN_SPACES_BUCKET_NAME}
  cdn-endpoint: ${DIGITAL_OCEAN_SPACES_CDN_ENDPOINT}

management:
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  metrics:
    enabled:
      spring.batch: false
  prometheus:
    metrics:
      export:
        enabled: true

API:
  VERSION: ${BACKEND_API_VERSION}


keycloak-initializer:
  initialize-on-startup: true
  master-realm: ${KEYCLOAK_INITIALIZER_MASTER_REALM}
  application-realm: ${KEYCLOAK_INITIALIZER_APPLICATION_REALM}
  client-id: ${KEYCLOAK_INITIALIZER_CLIENT_ID}
  username: ${KEYCLOAK_INITIALIZER_USERNAME}
  password: ${KEYCLOAK_INITIALIZER_PASSWORD}
  url: ${KEYCLOAK_INITIALIZER_URL}


bucket4j:
  enabled: false
  filters:
    - cache-name: rate-limit-buckets
      url: ^/api/.*
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "{ \"error\": \"Rate limit exceeded. Try again later.\" }"
      http-response-headers:
        X-Rate-Limit-Remaining: "#{getAvailableTokens()}"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 20
              time: 1
              unit: minutes
              refill-speed: interval


keycloak:
  frontend:
    client-id: ${KEYCLOAK_FRONTEND_CLIENT}
    redirect-uri: ${KEYCLOAK_FRONTEND_REDIRECT_URI}
    web-origin: ${KEYCLOAK_FRONTEND_WEB_ORIGIN},${KEYCLOAK_FRONTEND_WEB_ORIGIN_LOCALHOST}
  client-id: ${KEYCLOAK_BACKEND_CLIENT}
  redirect-uri: ${KEYCLOAK_BACKEND_REDIRECT_URI}
  web-origin: ${KEYCLOAK_BACKEND_WEB_ORIGIN}
  secret: ${KEYCLOAK_BACKEND_SECRET}
  admin:
    userName: ${KEYCLOAK_BACKEND_ADMIN_USERNAME}
    email: ${KEYCLOAK_BACKEND_ADMIN_EMAIL}
    password: ${KEYCLOAK_BACKEND_ADMIN_PASSWORD}
    firstName: ${KEYCLOAK_BACKEND_ADMIN_FIRST_NAME}
    lastName: ${KEYCLOAK_BACKEND_ADMIN_LAST_NAME}
  service:
    userName: ${KEYCLOAK_BACKEND_SERVICE_USERNAME}
    email: ${KEYCLOAK_BACKEND_SERVICE_EMAIL}
    password: ${KEYCLOAK_BACKEND_SERVICE_PASSWORD}
    firstName: ${KEYCLOAK_BACKEND_SERVICE_FIRST_NAME}
    lastName: ${KEYCLOAK_BACKEND_SERVICE_LAST_NAME}
  config:
    output-path: src/main/resources/config


spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s,recordStats
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout:
        30000
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI}

  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  application:
    name: echno_backend
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml


server:
  tomcat:
    threads:
      max: 150
    accept-count: 100
    connection-timeout: 20000
  port: 8080
  forward-headers-strategy: FRAMEWORK
  servlet:
    context-path: /

logging:
  file:
    name: /var/log/echno_backend.log
  level:
    root: WARN
    org.springframework: WARN
    org.springframework.security: INFO
    org.hibernate: WARN
    org.tornotron: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  config: classpath:logback-spring.xml

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}