jwt:
  auth:
    converter:
      resource-id: echno-app
      principle-attribute: preferred_username

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI}

  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  application:
    name: echno_backend
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  servlet:
    context-path: /

logging:
  file:
    name: /var/log/echno_backend.log
  level:
    root: WARN
    org.springframework: WARN
    org.springframework.security: INFO
    org.hibernate: WARN
    org.tornotron: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  config: classpath:logback-spring.xml