management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/echnoRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  application:
    name: echno_backend
  datasource:
    url: jdbc:postgresql://localhost:5432/echno_database
    username: root
    password: password
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8081
  forward-headers-strategy: native
logging:
  file:
    name: /var/log/echno_backend.log
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.tornotron: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
  config: classpath:logback-spring.xml