package org.tornotron.echno_backend.receipt;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.tornotron.echno_backend.common.response.ApiResponse;
import org.tornotron.echno_backend.receipt.dto.ReceiptCreationDto;
import org.tornotron.echno_backend.receipt.dto.ReceiptDto;
import org.tornotron.echno_backend.receipt.dto.ReceiptUpdateDto;
import org.tornotron.echno_backend.common.pagination.UnpagedResultCap;

import java.util.List;

@RestController
@Validated
@RequestMapping("/api/v1/receipts/web")
@Tag(
        name = "Receipts",
        description = "Money received against a project or the organization: payments, advances, security "
                + "deposits and refunds, with the payer, tax breakdown and an optional link to a project, "
                + "payment, invoice or customer. Read access requires tenant membership; creating, updating "
                + "and deleting are restricted to system-admin or project-manager."
)
public class ReceiptControllerWeb {

    private final ReceiptService receiptService;

    public ReceiptControllerWeb(ReceiptService receiptService) {
        this.receiptService = receiptService;
    }

    @GetMapping
    @PreAuthorize("@orgSecurity.isMemberOfCurrentTenant() or @orgSecurity.hasAnyOrgRoleForCurrentTenant('system-admin','project-manager')")
    @Operation(
            summary = "List all receipts",
            description = "Returns at most 500 rows. X-Total-Count carries the true total and X-Result-Capped is set when rows were left out; use the paginated variant for a complete result."
    )
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Receipts returned"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Caller lacks the required role in the current tenant")
    })
    public ResponseEntity<List<ReceiptDto>> readAllReceipts() {
        return UnpagedResultCap.respond(receiptService.getPaginated(
                0, UnpagedResultCap.MAX_ROWS, null, null));
    }

    @GetMapping("/paginated")
    @PreAuthorize("@orgSecurity.isMemberOfCurrentTenant() or @orgSecurity.hasAnyOrgRoleForCurrentTenant('system-admin','project-manager')")
    @Operation(
            summary = "List receipts, paginated and filterable",
            description = "Returns a single page of receipts. Supports a free-text search over the receipt "
                    + "number and the received-from name, and filtering by status."
    )
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Page of receipts returned"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Caller lacks the required role in the current tenant")
    })
    public ResponseEntity<Page<ReceiptDto>> readAllReceiptsPaginated(
            @RequestParam(defaultValue = "0") int pageNo,
            @RequestParam(defaultValue = "10") int pageSize,
            @RequestParam(required = false) String search,
            @RequestParam(required = false) String status) {
        return new ResponseEntity<>(receiptService.getPaginated(pageNo, pageSize, search, status), HttpStatus.OK);
    }

    @GetMapping("/{id}")
    @PreAuthorize("@orgSecurity.isMemberOfCurrentTenant() or @orgSecurity.hasAnyOrgRoleForCurrentTenant('system-admin','project-manager')")
    @Operation(
            summary = "Get a receipt by id",
            description = "Returns a single receipt with its payer, tax breakdown and optional links."
    )
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Receipt found"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Caller lacks the required role in the current tenant"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "No receipt with the given id")
    })
    public ResponseEntity<ReceiptDto> readAReceipt(@PathVariable Long id) {
        return new ResponseEntity<>(receiptService.getById(id), HttpStatus.OK);
    }

    @PostMapping
    @PreAuthorize("@orgSecurity.hasAnyOrgRoleForCurrentTenant('system-admin','project-manager')")
    @Operation(
            summary = "Create a receipt",
            description = "Creates a receipt with its payer, tax breakdown and optional links. The receipt "
                    + "number is generated by the server."
    )
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "201", description = "Receipt created"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "receivedFrom or amount is missing"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Caller lacks the required role in the current tenant")
    })
    public ResponseEntity<ReceiptDto> createReceipt(@Valid @RequestBody ReceiptCreationDto creationDto) {
        return new ResponseEntity<>(receiptService.create(creationDto), HttpStatus.CREATED);
    }

    @PutMapping("/{id}")
    @PreAuthorize("@orgSecurity.hasAnyOrgRoleForCurrentTenant('system-admin','project-manager')")
    @Operation(
            summary = "Update a receipt",
            description = "Replaces the receipt's editable details with the given payload. The receipt "
                    + "number is immutable."
    )
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Receipt updated"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "receivedFrom or amount is missing"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Caller lacks the required role in the current tenant"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "No receipt with the given id")
    })
    public ResponseEntity<ReceiptDto> updateReceipt(@PathVariable Long id,
                                                    @Valid @RequestBody ReceiptUpdateDto updateDto) {
        return new ResponseEntity<>(receiptService.update(id, updateDto), HttpStatus.OK);
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("@orgSecurity.hasAnyOrgRoleForCurrentTenant('system-admin','project-manager')")
    @Operation(
            summary = "Delete a receipt",
            description = "Deletes the receipt with the given id."
    )
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Receipt deleted"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "Caller lacks the required role in the current tenant"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "No receipt with the given id")
    })
    public ResponseEntity<ApiResponse> deleteReceipt(@PathVariable Long id) {
        receiptService.delete(id);
        return ResponseEntity.status(HttpStatus.OK)
                .body(new ApiResponse("Receipt with id: " + id + " has been deleted"));
    }
}
